<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KpicCafeteria.Application\KpicCafeteria.Application.csproj" />
    <ProjectReference Include="..\KpicCafeteria.Infrastructure\KpicCafeteria.Infrastructure.csproj" />
    <ProjectReference Include="..\KpicCafeteria.Documents\KpicCafeteria.Documents.csproj" />
    <ProjectReference Include="..\KpicCafeteria.HancomWorker\KpicCafeteria.HancomWorker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
