// <auto-generated />
using System;
using KpicCafeteria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KpicCafeteria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CafeteriaDbContext))]
    [Migration("20260815144059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.BackupRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("backup_type");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<int?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoredFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_filename");

                    b.HasKey("Id");

                    b.ToTable("backup_records", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.DataArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_to");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<int?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoredFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_filename");

                    b.HasKey("Id");

                    b.ToTable("data_archives", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type");

                    b.Property<int?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_valid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_filename");

                    b.Property<string>("PlaceholderSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("placeholder_summary");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredFilename")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_filename");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_message");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("DocumentType");

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.ImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("errors");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<bool>("AnalysisExcluded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("analysis_excluded");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_unit");

                    b.Property<double?>("KgFactor")
                        .HasColumnType("REAL")
                        .HasColumnName("kg_factor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_status");

                    b.Property<string>("SourceCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_code");

                    b.Property<string>("StatGroup")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("stat_group");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SourceCode")
                        .IsUnique();

                    b.HasIndex("StatGroup");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.IngredientAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Source")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("IngredientId");

                    b.ToTable("ingredient_aliases", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealActual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actual_count");

                    b.Property<int>("MealServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_service_id");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("MealServiceId")
                        .IsUnique();

                    b.ToTable("meal_actuals", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConceptTitle")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("concept_title");

                    b.Property<string>("CookingOutputAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cooking_output_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MealPlanOutputAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("meal_plan_output_at");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("meal_type");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planned_count");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_date");

                    b.Property<TimeOnly?>("ServiceTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_time");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MealType");

                    b.HasIndex("ServiceDate");

                    b.HasIndex("ServiceDate", "MealType")
                        .IsUnique()
                        .HasDatabaseName("uq_meal_service_date_type");

                    b.ToTable("meal_services", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealServiceMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookingInstruction")
                        .HasColumnType("TEXT")
                        .HasColumnName("cooking_instruction");

                    b.Property<string>("CookingNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("cooking_note");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_representative");

                    b.Property<int>("MealServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_service_id");

                    b.Property<int?>("MenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_id");

                    b.Property<string>("MenuNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_name_snapshot");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipe_id");

                    b.Property<string>("RecipeNameSnapshot")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("recipe_name_snapshot");

                    b.Property<int?>("RecipeVersionSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipe_version_snapshot");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("MealServiceId");

                    b.HasIndex("MenuId");

                    b.HasIndex("RecipeId");

                    b.ToTable("meal_service_menus", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealServiceMenuIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_name_snapshot");

                    b.Property<int>("MealServiceMenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_service_menu_id");

                    b.Property<double?>("QuantityPer100")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity_per_100");

                    b.Property<double?>("QuantityTotal")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity_total");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("SourceNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_note");

                    b.Property<string>("SourceRow")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_row");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealServiceMenuId");

                    b.ToTable("meal_service_menu_ingredients", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealTypeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultPlannedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_planned_count");

                    b.Property<TimeOnly?>("DefaultServiceTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_service_time");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("meal_type_settings", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_status");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SourceCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_code");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("SourceCode")
                        .IsUnique();

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.OrderGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_date");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_name_snapshot");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_date");

                    b.Property<double?>("OrderQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("order_quantity");

                    b.Property<string>("OrderUnit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_unit");

                    b.Property<string>("RequiredUnit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("required_unit");

                    b.Property<double?>("TotalRequiredQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("total_required_quantity");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("order_groups", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_date");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_name_snapshot");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_date");

                    b.Property<int?>("OrderGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_group_id");

                    b.Property<double?>("OrderQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("order_quantity");

                    b.Property<string>("OrderUnit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_unit");

                    b.Property<double?>("RequiredQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("required_quantity");

                    b.Property<string>("RequiredUnit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("required_unit");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("OrderGroupId");

                    b.HasIndex("ServiceDate");

                    b.HasIndex("Status");

                    b.HasIndex("ServiceDate", "IngredientId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_item_date_ingredient");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.PreservationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("collected_at");

                    b.Property<string>("CollectionTime")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("collection_time");

                    b.Property<string>("CollectorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("collector_name");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("DisposalAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disposal_at");

                    b.Property<string>("FreezerTemperature")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("freezer_temperature");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manager_name");

                    b.Property<int>("MealServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_service_id");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MealServiceId")
                        .IsUnique();

                    b.ToTable("preservation_records", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("CompositionKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("composition_key");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("CompositionKey");

                    b.HasIndex("IsDefault");

                    b.HasIndex("MenuId");

                    b.HasIndex("MenuId", "CompositionKey")
                        .IsUnique()
                        .HasDatabaseName("uq_recipe_menu_composition");

                    b.HasIndex("MenuId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_recipe_menu_version");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<double?>("QuantityPer100")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity_per_100");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipe_id");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_status");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.IngredientAlias", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("Aliases")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealActual", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.MealService", "Service")
                        .WithOne("Actual")
                        .HasForeignKey("KpicCafeteria.Domain.Entities.MealActual", "MealServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealServiceMenu", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.MealService", "Service")
                        .WithMany("Menus")
                        .HasForeignKey("MealServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KpicCafeteria.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KpicCafeteria.Domain.Entities.Recipe", "SourceRecipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");

                    b.Navigation("Service");

                    b.Navigation("SourceRecipe");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealServiceMenuIngredient", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KpicCafeteria.Domain.Entities.MealServiceMenu", "ServiceMenu")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealServiceMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ServiceMenu");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.OrderGroup", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KpicCafeteria.Domain.Entities.OrderGroup", "OrderGroup")
                        .WithMany()
                        .HasForeignKey("OrderGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ingredient");

                    b.Navigation("OrderGroup");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.PreservationRecord", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.MealService", "Service")
                        .WithOne("Preservation")
                        .HasForeignKey("KpicCafeteria.Domain.Entities.PreservationRecord", "MealServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.Menu", "Menu")
                        .WithMany("Recipes")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("KpicCafeteria.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KpicCafeteria.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealService", b =>
                {
                    b.Navigation("Actual");

                    b.Navigation("Menus");

                    b.Navigation("Preservation");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.MealServiceMenu", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("KpicCafeteria.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
